# Generated by Django 5.2.8 on 2025-11-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
